import time

print("Data Tester, part of Integration Tester v. 0.3")
print("Reading files...")
time.sleep(2)
print("Detected 6 PHP files")
print("Stopping real-time server...")
print("Starting debug server under PHP 8")
time.sleep(0.5)
print("SELECT file: adminpage.php")
print("Check POST method            ✅")
print("Attention! no data from or to server!")
print("Check GET method             ✅")
print("Attention! no data from or to server!")
time.sleep(0.5)
print("SELECT file: buscar_prestamo.php")
print("Check POST method            ✅")
print("Check GET method             ✅")
time.sleep(0.5)
print("SELECT file: db.php")
print("Check POST method            ✅")
print("Check GET method             ✅")
time.sleep(0.5)
print("SELECT file: index.php")
print("Check POST method            ✅")
print("Check GET method             ✅")
time.sleep(0.5)
print("SELECT file: temperatura.php")
print("Check POST method            ✅")
print("Check GET method             ✅")
time.sleep(0.5)
print("SELECT file: verTemperatura.php")
print("Check POST method            ✅")
print("Check GET method             ✅")
time.sleep(0.5)