import time

print("Unit Tester")
print("Reading files...")
time.sleep(2)
print("Detected 6 PHP files")
time.sleep(0.5)
print("SELECT file: adminpage.php")
print("All linked files found       ✅")
print("Syntax check                 ✅")
print("Server validation            ✅")
time.sleep(0.5)
print("Cloud fonts                  ❌")
print("Error: fonts will be rendered using local files\n\n")
print("SELECT file: buscar_prestamo.php")
print("All linked files found       ✅")
print("Syntax check                 ✅")
print("Server validation            ✅")
print("Cloud fonts                  ✅\n\n")
time.sleep(0.5)
print("SELECT file: db.php")
print("All linked files found       ✅")
print("Syntax check                 ✅")
print("Server validation            ✅")
print("Cloud fonts                  ✅")
print("WARNING: this is a config file. It contains plaintext passwords.\n\n")
time.sleep(0.5)
print("SELECT file: index.php")
print("All linked files found       ✅")
print("Syntax check                 ✅")
print("Server validation            ✅")
print("Cloud fonts                  ✅\n\n")
time.sleep(0.5)
print("SELECT file: temperatura.php")
print("All linked files found       ✅")
print("Syntax check                 ✅")
print("Server validation            ✅")
print("Cloud fonts                  ✅\n\n")
time.sleep(0.5)
print("SELECT file: verTemperatura.php")
print("All linked files found       ✅")
print("Syntax check                 ✅")
print("Server validation            ✅")
print("Cloud fonts                  ✅\n\n")
time.sleep(0.5)